spring.application.name=artconnect-api-gateway
server.port=9090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.cloud.gateway.server.webflux.routes[0].id=artconnect-auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://artconnect-auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

jwt.secret=8aR9xP2mL5vQ7wXe1Nc4Hd8YkT6uFs3Bg9ZjVr2LmQ5Px8As6Nf7Kb1Dw4Hy9Rt
jwt.access-token-expiration=60000
jwt.refresh-token-expiration=604800000


management.endpoints.web.exposure.include=*
